// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectOneMil.Data;

#nullable disable

namespace ProjectOneMil.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectOneMil.Data.MyTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Column1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Column10")
                        .HasColumnType("uuid");

                    b.Property<int>("Column2")
                        .HasColumnType("integer");

                    b.Property<decimal>("Column3")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Column4")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Column5")
                        .HasColumnType("boolean");

                    b.Property<string>("Column6")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Column7")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Column8")
                        .HasColumnType("integer");

                    b.Property<decimal>("Column9")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("onemildata");
                });
#pragma warning restore 612, 618
        }
    }
}
